version: '2'
services:
  jhreact-app:
    image: jhreact
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhreact-postgresql:5432/jhreact
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhreact-postgresql:
    extends:
      file: postgresql.yml
      service: jhreact-postgresql
